name: Generate Pacman Game

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: bossjobmatt

      - name: Move pacman-contribution-graph.svg to dist/pacman/
        run: |
          mkdir -p dist/pacman
          shopt -s nullglob
          files=(pacman-contribution-graph*.svg)
          if [ ${#files[@]} -gt 0 ]; then
            mv "${files[@]}" dist/pacman/
          else
            echo "No SVG files found to move."
          fi

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}